language: node_js
node_js:
  - "12"

before_install: cd cookbook

install:
  - npm install -g markdownlint-cli
  - npm ci

script:
  - markdownlint **/*.mdx
  - npm run build
  - docker run --rm -d --name gatsby -p 8888:80 -v $(pwd)/public:/usr/local/apache2/htdocs$SITE_PREFIX httpd:2.4

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: cookbook/public
    github_token: $GITHUB_TOKEN
    github_url: github.com
    committer_from_gh: true
    target_branch: gh-pages
    on:
      branch: main
